[debug] [2023-12-06T08:59:56.787Z] ----------------------------------------------------------------------
[debug] [2023-12-06T08:59:56.793Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\bozhi\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2023-12-06T08:59:56.794Z] CLI Version:   12.9.1
[debug] [2023-12-06T08:59:56.795Z] Platform:      win32
[debug] [2023-12-06T08:59:56.796Z] Node Version:  v18.17.1
[debug] [2023-12-06T08:59:56.810Z] Time:          Wed Dec 06 2023 10:59:56 GMT+0200 (Източноевропейско стандартно време)
[debug] [2023-12-06T08:59:56.811Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-12-06T08:59:56.817Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-12-06T08:59:57.073Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-12-06T08:59:57.074Z] > authorizing via signed-in user (ffrolshki@gmail.com)
[debug] [2023-12-06T08:59:57.075Z] [iam] checking project boxer-club for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-12-06T08:59:57.077Z] > refreshing access token with scopes: []
[debug] [2023-12-06T08:59:57.078Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-12-06T08:59:57.079Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-12-06T08:59:57.092Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: getaddrinfo ENOTFOUND firebase-public.firebaseio.com
[warn] !  Unable to fetch the CLI MOTD and remote config. 
[debug] [2023-12-06T08:59:57.095Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2023-12-06T08:59:57.099Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------172980358183010083814182","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-12-06T08:59:57.100Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-12-06T08:59:57.100Z] > refreshing access token with scopes: []
[debug] [2023-12-06T08:59:57.101Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-12-06T08:59:57.101Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-12-06T08:59:57.126Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------128657353361730781107297","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-12-06T08:59:57.126Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[error] 
[error] Error: Assertion failed: resolving hosting target of a site with no site name or target name. This should have caused an error earlier
